### PR TITLE
Fix broken website layout #274

### PR DESCRIPTION
**Pull request by guacjack**
screen shot 2016-03-19 at 15 41 21
screen shot 2016-03-19 at 15 41 32
screen shot 2016-03-19 at 15 41 44
screen shot 2016-03-19 at 17 07 03

See above for how this PR fixes how it looks on iPhone 4, looks the same on iPhone 6 also.

### CODE REVIEW

**Comment by guacjack** [comment]
https://github.com/cyclejs/core/issues/274

**Comment by Cmdv** [comment]
nice one @guacjack good work :)

**Comment by staltz** [comment]
Hi @guacjack, thanks a lot for the initiative. Since you're at it, can you fix the lack of any lateral padding for mobile screens? It looks like this:

screen shot 2016-03-20 at 19 42 48

**Comment by guacjack** [comment]
@staltz there was an issue on mobile where long `<code></code>` tags were not wrapping so made the display look weird. As seen below
screen shot 2016-03-21 at 12 26 59

this was due to the text not being allowed to be wrapped due to it being a long snippet of code

This latest commit adds the padding as well as allowing the text to wrap as seen here
screen shot 2016-03-21 at 12 28 05
screen shot 2016-03-21 at 12 28 15

**Comment by staltz** [comment]
Merged. Many thanks @guacjack !

**Comment by Cmdv** [comment]
well done @guacjack first merge to OSS project 👍💪👌 First of many I hope 😊

**Pull request merged**
